language: python
python:
#  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
sudo: false
script: nosetests test --verbose
notifications:
  email:
    - peter_bergmann@posteo.de

# public repository on Travis CI
install:
  - pip install codecov

script:
  - coverage run test/test_nose.py

after_success:
- codecov
